### ISSUE TITLE
t_plug var depends on hardcoded path

### ISSUE THREAD

**Issue by z0rc** [MikeDacre/tmux-zsh-vim-titles#1]
https://github.com/MikeDacre/tmux-zsh-vim-titles/blob/master/unified-titles.plugin.zsh#L8 uses hardcoded path.

Unfortunately this isn't going to match with configuration I'm using, where
```
% type tmux 
tmux is an alias for tmux -f /home/igor/.local/dotfiles/tmux/tmux.conf
```
and plugin directory is custom one as I'm not using plugin managers. All in order to keep `$HOME` clean from unnecessary dotfiles/dotfolders.

How do you think this can be solved?

**Comment by MikeDacre** [comment]
Possibly the best way is to define yet another variable such that the user can force tmux mode on. I am not sure though, I want to think about this a little more.

**Comment by MikeDacre** [comment]
I changed the code to detect if the tmux plugin has already been loaded and then to use the locally installed version to refresh the tmux titles. This isn't perfect, but it is good enough and it should solve this issue.
