### ISSUE TITLE
Switch to hostname cli utility

### ISSUE THREAD

**Issue by z0rc** [MikeDacre/tmux-zsh-vim-titles#2]
https://github.com/MikeDacre/tmux-zsh-vim-titles/blob/master/unified-titles.plugin.zsh#L32

This python script is unnecessary heavy and slows down shell startup significantly. `hostname` utility should be able to provide all needed information. If `hostname` doesn't provide right info, then you have much more bigger problems then trying to figure the right hostname with custom python script.

**Comment by z0rc** [comment]
I just noticed, that mentioned python script does `zsh_title_hosts` translation in addition to hostname detection. At this case it won't be simple switch to `hostname`.

Still I cannot afford to run any python script at shell startup no matter how small or fast it is. Also I'm not planning to use `zsh_title_hosts` feature.

**Comment by z0rc** [comment]
Also $HOSTNAME isn't set by default, there is no guarantee that this variable exists.
```
% ./get_hoststring.py 
Traceback (most recent call last):
  File "./get_hoststring.py", line 105, in <module>
    host_string = main()
  File "./get_hoststring.py", line 99, in main
    host_str = h.replace('#h', get_hostname())
  File "./get_hoststring.py", line 85, in get_hostname
    host = os.environ.get('HOSTNAME').split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by MikeDacre** [comment]
The use of `HOSTNAME` is a bug, I will fix it. I am not going to drop the python script though, it allows for users to configure shortened host names, which is sometimes very valuable. What I can do it protect it such that the python script is only called if necessary.

**Comment by MikeDacre** [comment]
Done, we now only call the python script if absolutely necessary, in both the ZSH and the tmux components.

**Comment by MikeDacre** [comment]
Also, just FYI, the execution time of the python script was tiny, like really tiny. If your machine is so slow that that time was an issue, you will likely have problems with other parts of the plugin, as we do some login on every new prompt, and that ZSH code is likely slower than the python code. Sadly, this plugin might not be best for you given that. Thanks for all the issue submissions though.
