### ISSUE TITLE
Set window title without tmux

### ISSUE THREAD

**Issue by z0rc** [MikeDacre/tmux-zsh-vim-titles#6]
Seems that window title change entirely depends on tmux. Would it be possible to add possibility to set windows title when running zsh only?

**Comment by z0rc** [comment]
A bit more clarification. I tested each print from https://github.com/MikeDacre/tmux-zsh-vim-titles/blob/master/unified-titles.plugin.zsh#L65-L73, none of them works with KDE's konsole and TERM=xterm-256color.
But it's still possible to do so by issuing `echo -ne "\033]30;$PWD\007"`, this command successfully changes konsole's windows title. I don't know how portable is this and whether it works with other terminal emulators.

**Comment by MikeDacre** [comment]
Hi @z0rc, apologies for the delay, I was travelling.

The window title actually just refers to the tmux window, not the application window. The application window title is the terminal title, so you are right that the window title is tmux specific.

As for konsole, it should be possible to use the ASCII control characters you suggest, I would need to detect that konsole is being used though. Do you know of a way to detect that konsole is being used from the command line?

**Comment by z0rc** [comment]
```
% env | grep KONSOLE
KONSOLE_DBUS_SERVICE=:1.64
KONSOLE_DBUS_SESSION=/Sessions/1
KONSOLE_DBUS_WINDOW=/Windows/1
KONSOLE_PROFILE_NAME=Main
```
For example vim terminus uses those env vars to detect Konsole. See https://github.com/wincent/terminus/search?utf8=%E2%9C%93&q=KONSOLE&type=
